import { useEffect, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { adminJson, adminRequest, receiptUrl } from '../api/admin'
import type { OrderDetail, OrderStatus } from '../types/admin'
import { money } from '../utils/money'
import { AdminError, AdminLoading, StatusBadge } from './adminUi'
import { dateTime, label } from './adminFormat'
import { AccessibleModal } from '../components/AccessibleModal'

const nextStatus: Partial<Record<OrderStatus, OrderStatus>> = { NEW: 'CONFIRMED', CONFIRMED: 'PREPARING', PREPARING: 'READY', ON_THE_WAY: 'DELIVERED' }
const timelineSteps = [['createdAt','Pedido recibido'],['confirmedAt','Confirmado'],['preparedAt','Preparación iniciada'],['readyAt','Listo'],['onTheWayAt','En camino'],['deliveredAt','Entregado'],['cancelledAt','Cancelado']] as const
export function AdminOrderDetailPage() {
  const { publicNumber = '' } = useParams(); const [order, setOrder] = useState<OrderDetail>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [receipt, setReceipt] = useState<string>(); const [reasonAction, setReasonAction] = useState<'reject' | 'cancel'>()
  const load = () => { setError(''); adminRequest<OrderDetail>(`/orders/${encodeURIComponent(publicNumber)}`).then(setOrder).catch(() => setError('El pedido no existe o no se pudo consultar.')) }
  useEffect(() => { adminRequest<OrderDetail>(`/orders/${encodeURIComponent(publicNumber)}`).then(setOrder).catch(() => setError('El pedido no existe o no se pudo consultar.')) }, [publicNumber]); useEffect(() => () => { if (receipt) URL.revokeObjectURL(receipt) }, [receipt])
  async function transition(status: OrderStatus, reason?: string) { setBusy(true); setError(''); try { setOrder(await adminJson<OrderDetail>(`/orders/${publicNumber}/status`, 'PATCH', { status, reason })) } catch { setError('No fue posible cambiar el estado. Verifica la transición.') } finally { setBusy(false) } }
  async function review(action: 'approve' | 'reject', reason?: string) { setBusy(true); try { setOrder(await adminJson<OrderDetail>(`/orders/${publicNumber}/payment/${action}`, 'POST', action === 'reject' ? { reason } : {})) } catch { setError('No fue posible revisar el pago.') } finally { setBusy(false) } }
  async function submitReason(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get('reason')).trim(); if (!reason || !reasonAction) return; setReasonAction(undefined); if (reasonAction === 'reject') await review('reject', reason); else await transition('CANCELLED', reason) }
  async function showReceipt() { try { setReceipt(await receiptUrl(publicNumber)) } catch { setError('No pudimos abrir el comprobante.') } }
  if (error && !order) return <AdminError message={error} retry={load} />
  if (!order) return <AdminLoading label="Abriendo pedido…" />
  let next = nextStatus[order.status]; if (order.status === 'READY') next = order.deliveryType === 'DELIVERY' ? 'ON_THE_WAY' : 'DELIVERED'
  return <><Link to="/admin/orders" className="back-link">← Volver a pedidos</Link><header className="detail-header"><div><p className="eyebrow">PEDIDO</p><h1>{order.publicNumber}</h1><p>Creado {dateTime(order.createdAt)}</p></div><StatusBadge value={order.status} /></header>{error && <div className="admin-alert" role="alert">{error}</div>}
    <div className="detail-grid"><section className="admin-panel detail-main"><h2>Productos</h2>{order.items.map((item, index) => <article className="order-item" key={`${item.name}-${index}`}><b>{item.quantity}×</b><div><strong>{item.name}</strong>{item.extras.map(extra => <small key={extra.name}>+ {extra.quantity} {extra.name}</small>)}{item.notes && <em>“{item.notes}”</em>}</div><span>{money(item.subtotal)}</span></article>)}<dl className="totals"><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Descuento</dt><dd>− {money(order.discount)}</dd></div><div><dt>Domicilio</dt><dd>{money(order.deliveryFee)}</dd></div><div className="grand-total"><dt>Total</dt><dd>{money(order.total)}</dd></div></dl></section>
      <aside className="detail-side"><section className="admin-panel"><h2>Cliente y entrega</h2><dl className="info-list"><div><dt>Cliente</dt><dd>{order.customerName}</dd></div><div><dt>Teléfono</dt><dd>{order.customerPhone}</dd></div><div><dt>Modalidad</dt><dd>{label(order.deliveryType)}</dd></div><div><dt>Dirección / referencia</dt><dd>{order.deliveryAddress || 'Recoge en el local'}</dd></div></dl></section>
        {order.payment && <section className="admin-panel"><div className="panel-title"><h2>Pago</h2><StatusBadge value={order.payment.status} /></div><dl className="info-list"><div><dt>Método</dt><dd>{label(order.payment.method)}</dd></div><div><dt>Monto</dt><dd>{money(order.payment.amount)}</dd></div>{order.payment.reviewerName && <div><dt>Revisó</dt><dd>{order.payment.reviewerName} · {dateTime(order.payment.reviewedAt)}</dd></div>}{order.payment.rejectionReason && <div><dt>Motivo</dt><dd>{order.payment.rejectionReason}</dd></div>}</dl>{order.payment.receiptAvailable && <button className="secondary block" onClick={showReceipt}>Ver comprobante protegido</button>}{order.payment.status === 'UNDER_REVIEW' && <div className="button-row"><button className="danger" disabled={busy} onClick={() => setReasonAction('reject')}>Rechazar</button><button className="primary" disabled={busy} onClick={() => void review('approve')}>Aprobar</button></div>}</section>}
        <section className="admin-panel"><h2>Seguimiento</h2><ol className="order-timeline">{timelineSteps.map(([key, text]) => <li className={order.timeline[key] ? 'done' : ''} key={key}><i>{order.timeline[key] ? '✓' : '·'}</i><div><strong>{text}</strong><small>{dateTime(order.timeline[key])}</small></div></li>)}</ol>{order.timeline.cancellationReason && <div className="admin-alert">Motivo: {order.timeline.cancellationReason}</div>}</section>
        <section className="admin-panel"><h2>Actualizar estado</h2>{next ? <button className="primary block" disabled={busy} onClick={() => void transition(next!)}>Marcar como {label(next)}</button> : <p className="muted">No hay una transición siguiente disponible.</p>}{!['DELIVERED','CANCELLED'].includes(order.status) && <button className="text-danger" disabled={busy} onClick={() => setReasonAction('cancel')}>Cancelar pedido</button>}</section></aside></div>
    {receipt && <AccessibleModal variant="receipt" label="Comprobante de pago" onClose={() => setReceipt(undefined)}><button onClick={() => setReceipt(undefined)} aria-label="Cerrar comprobante">×</button><img src={receipt} alt="Comprobante de transferencia" /></AccessibleModal>}
    {reasonAction && <AccessibleModal labelledBy="reason-modal-title" onClose={() => setReasonAction(undefined)}><form className="modal-card admin-form" onSubmit={submitReason}><div className="panel-title wide"><h2 id="reason-modal-title">{reasonAction === 'reject' ? 'Rechazar comprobante' : 'Cancelar pedido'}</h2><button type="button" className="icon-close" aria-label="Cerrar" onClick={() => setReasonAction(undefined)}>×</button></div><label className="wide">Motivo<textarea name="reason" maxLength={500} required autoFocus /></label><div className="form-actions wide"><button type="button" className="secondary" onClick={() => setReasonAction(undefined)}>Volver</button><button className="danger" disabled={busy}>Confirmar</button></div></form></AccessibleModal>}
  </>
}
