import { useEffect, useState, type FormEvent } from 'react'
import { adminJson, adminRequest, uploadAdminFile } from '../api/admin'
import type { HoursView, SettingsView } from '../types/admin'
import { PageTitle } from './AdminDashboardPage'
import { AdminError, AdminLoading } from './adminUi'

const days = [['MONDAY','Lunes'],['TUESDAY','Martes'],['WEDNESDAY','Miércoles'],['THURSDAY','Jueves'],['FRIDAY','Viernes'],['SATURDAY','Sábado'],['SUNDAY','Domingo']]
export function AdminSettingsPage() {
  const [settings, setSettings] = useState<SettingsView>(); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false)
  const load = () => { setError(''); adminRequest<SettingsView>('/settings').then(setSettings).catch(() => setError('No pudimos cargar la configuración.')) }; useEffect(() => { adminRequest<SettingsView>('/settings').then(setSettings).catch(() => setError('No pudimos cargar la configuración.')) }, [])
  function hoursFor(day: string): HoursView { return settings?.hours.find(item => item.dayOfWeek === day && item.slotNumber === 1) ?? { dayOfWeek: day, slotNumber: 1, opensAt: '11:00', closesAt: '22:00', closed: false } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const hours = days.map(([day]) => ({ dayOfWeek: day, slotNumber: 1, closed: f.get(`closed-${day}`) === 'on', opensAt: f.get(`closed-${day}`) === 'on' ? null : String(f.get(`opens-${day}`)), closesAt: f.get(`closed-${day}`) === 'on' ? null : String(f.get(`closes-${day}`)) })); const body = { tradeName: String(f.get('tradeName')), description: String(f.get('description')), phone: String(f.get('phone')), whatsapp: String(f.get('whatsapp')), address: String(f.get('address')), instagram: String(f.get('instagram')), facebook: String(f.get('facebook')), baseDeliveryFee: Number(f.get('baseDeliveryFee')), estimatedPreparationMinutes: Number(f.get('estimatedPreparationMinutes')), timeZone: String(f.get('timeZone')), transferProvider: String(f.get('transferProvider')), transferAccountHolder: String(f.get('transferAccountHolder')), transferAccountReference: String(f.get('transferAccountReference')), hours }; setSaving(true); try { setSettings(await adminJson('/settings', 'PUT', body)); setSaved(true); window.setTimeout(() => setSaved(false), 2500) } catch { setError('No se pudo guardar. Revisa los campos y horarios.') } finally { setSaving(false) } }
  async function upload(file?: File) { if (!file) return; try { setSettings(await uploadAdminFile('/settings/qr', 'image', file)); setSaved(true) } catch { setError('El QR debe ser una imagen JPG, PNG o WebP válida.') } }
  if (error && !settings) return <AdminError message={error} retry={load} />
  if (!settings) return <AdminLoading label="Cargando configuración…" />
  return <><PageTitle eyebrow="NEGOCIO" title="Configuración" />{error && <div className="admin-alert" role="alert">{error}</div>}{saved && <div className="admin-success" role="status">Cambios guardados correctamente.</div>}<form className="settings-form" onSubmit={save}>
    <section className="admin-panel admin-form"><div className="wide"><p className="eyebrow">INFORMACIÓN PÚBLICA</p><h2>Datos del restaurante</h2></div><label>Nombre comercial<input name="tradeName" defaultValue={settings.tradeName} required /></label><label>Teléfono<input name="phone" defaultValue={settings.phone} required /></label><label className="wide">Descripción<textarea name="description" defaultValue={settings.description} /></label><label>WhatsApp<input name="whatsapp" defaultValue={settings.whatsapp} required /></label><label>Dirección<input name="address" defaultValue={settings.address} required /></label><label>Instagram<input name="instagram" defaultValue={settings.instagram} /></label><label>Facebook<input name="facebook" defaultValue={settings.facebook} /></label><label>Domicilio base<input name="baseDeliveryFee" type="number" min="0" defaultValue={settings.baseDeliveryFee} /></label><label>Preparación (minutos)<input name="estimatedPreparationMinutes" type="number" min="1" defaultValue={settings.estimatedPreparationMinutes} /></label><label>Zona horaria<input name="timeZone" defaultValue={settings.timeZone} required /></label></section>
    <section className="admin-panel admin-form"><div className="wide"><p className="eyebrow">TRANSFERENCIAS</p><h2>Datos de pago</h2></div><label>Proveedor<input name="transferProvider" defaultValue={settings.transferProvider} placeholder="Nequi, Daviplata…" /></label><label>Titular<input name="transferAccountHolder" defaultValue={settings.transferAccountHolder} /></label><label>Cuenta / referencia<input name="transferAccountReference" defaultValue={settings.transferAccountReference} /></label><label className="upload-field">QR de pago<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void upload(e.target.files?.[0])} /><small>{settings.paymentQrPath ? 'QR configurado' : 'Sin QR configurado'}</small></label></section>
    <section className="admin-panel hours-panel"><p className="eyebrow">ATENCIÓN</p><h2>Horarios</h2><div className="hours-list">{days.map(([day, name]) => { const value = hoursFor(day); return <div key={day}><strong>{name}</strong><label>Abre<input name={`opens-${day}`} type="time" defaultValue={value.opensAt?.slice(0,5)} /></label><label>Cierra<input name={`closes-${day}`} type="time" defaultValue={value.closesAt?.slice(0,5)} /></label><label className="check"><input name={`closed-${day}`} type="checkbox" defaultChecked={value.closed} /> Cerrado</label></div> })}</div></section>
    <div className="settings-save"><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar configuración'}</button></div></form></>
}
