import { useEffect, useState, type FormEvent } from 'react'
import { adminJson, adminRequest, uploadAdminFile } from '../api/admin'
import { useAdminAuth } from '../features/admin/admin-auth-context'
import type { CategoryView, ExtraView, ProductView } from '../types/admin'
import { money } from '../utils/money'
import { PageTitle } from './AdminDashboardPage'
import { AdminLoading, EmptyState, StatusBadge } from './adminUi'

export function AdminProductsPage() {
  const { user } = useAdminAuth(); const editable = user?.role === 'ADMIN'
  const [products, setProducts] = useState<ProductView[]>(); const [categories, setCategories] = useState<CategoryView[]>([]); const [extras, setExtras] = useState<ExtraView[]>([]); const [editing, setEditing] = useState<ProductView>(); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => { setError(''); Promise.all([adminRequest<ProductView[]>('/products'), adminRequest<CategoryView[]>('/categories'), adminRequest<ExtraView[]>('/extras')]).then(([p,c,e]) => { setProducts(p); setCategories(c); setExtras(e) }).catch(() => setError('No pudimos cargar el catálogo.')) }
  useEffect(() => { Promise.all([adminRequest<ProductView[]>('/products'), adminRequest<CategoryView[]>('/categories'), adminRequest<ExtraView[]>('/extras')]).then(([p,c,e]) => { setProducts(p); setCategories(c); setExtras(e) }).catch(() => setError('No pudimos cargar el catálogo.')) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { name: String(form.get('name')), slug: String(form.get('slug')), description: String(form.get('description')), price: Number(form.get('price')), categoryId: Number(form.get('categoryId')), available: form.get('available') === 'on', featured: form.get('featured') === 'on', extraIds: form.getAll('extraIds').map(Number) }; setSaving(true); try { if (editing) await adminJson(`/products/${editing.id}`, 'PUT', body); else await adminJson('/products', 'POST', body); setOpen(false); setEditing(undefined); load() } catch { setError('No fue posible guardar el producto. Revisa los datos.') } finally { setSaving(false) } }
  async function toggle(product: ProductView) { try { await adminJson(`/products/${product.id}/active`, 'PATCH', { active: !product.available }); load() } catch { setError('No se pudo actualizar la disponibilidad.') } }
  async function image(product: ProductView, file?: File) { if (!file) return; try { await uploadAdminFile(`/products/${product.id}/image`, 'image', file); load() } catch { setError('La imagen debe ser JPG, PNG o WebP y respetar el tamaño máximo.') } }
  return <><PageTitle eyebrow="CATÁLOGO" title="Productos" action={editable ? <button className="primary" onClick={() => { setEditing(undefined); setOpen(true) }}>Nuevo producto</button> : undefined} />{!editable && <div className="admin-note">Tu rol permite consultar productos, pero no modificarlos.</div>}{error && <div className="admin-alert" role="alert">{error}</div>}
    {!products ? <AdminLoading label="Cargando productos…" /> : !products.length ? <EmptyState text="Aún no hay productos." /> : <section className="catalog-grid">{products.map(product => <article className="admin-panel product-admin-card" key={product.id}><div className="product-thumb">{product.imagePath ? <img src={`${import.meta.env.VITE_API_URL ?? 'http://localhost:8080/api/v1'}/public/product-images/${product.imagePath}`} alt="" /> : <span>SF</span>}</div><div><div className="panel-title"><div><p className="eyebrow">{product.categoryName}</p><h2>{product.name}</h2></div><StatusBadge value={product.available ? 'APPROVED' : 'REJECTED'} /></div><p>{product.description}</p><strong className="price">{money(product.price)}</strong>{product.featured && <small className="featured">DESTACADO</small>}</div>{editable && <div className="card-actions"><button className="secondary" onClick={() => { setEditing(product); setOpen(true) }}>Editar</button><button className="secondary" onClick={() => void toggle(product)}>{product.available ? 'Marcar agotado' : 'Activar'}</button><label className="upload-button">Imagen<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void image(product, e.target.files?.[0])} /></label></div>}</article>)}</section>}
    {open && <div className="admin-modal" role="dialog" aria-modal="true" aria-label="Editor de producto"><form className="modal-card admin-form" onSubmit={submit}><div className="panel-title"><h2>{editing ? 'Editar producto' : 'Nuevo producto'}</h2><button type="button" className="icon-close" onClick={() => setOpen(false)}>×</button></div><label>Nombre<input name="name" defaultValue={editing?.name} required /></label><label>Slug<input name="slug" defaultValue={editing?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label className="wide">Descripción<textarea name="description" defaultValue={editing?.description} required /></label><label>Precio<input name="price" type="number" min="0" step="100" defaultValue={editing?.price} required /></label><label>Categoría<select name="categoryId" defaultValue={editing?.categoryId} required><option value="">Selecciona</option>{categories.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><fieldset className="wide"><legend>Extras permitidos</legend>{extras.map(extra => <label className="check" key={extra.id}><input name="extraIds" type="checkbox" value={extra.id} defaultChecked={editing?.extraIds.includes(extra.id)} />{extra.name}</label>)}</fieldset><label className="check"><input name="available" type="checkbox" defaultChecked={editing?.available ?? true} /> Disponible</label><label className="check"><input name="featured" type="checkbox" defaultChecked={editing?.featured} /> Destacado</label><div className="form-actions wide"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar producto'}</button></div></form></div>}
  </>
}
