import { useEffect, useState, type FormEvent } from 'react'
import { adminJson, adminRequest } from '../api/admin'
import type { CategoryView } from '../types/admin'
import { PageTitle } from './AdminDashboardPage'
import { AdminError, AdminLoading, EmptyState } from './adminUi'

export function AdminCategoriesPage() {
  const [items, setItems] = useState<CategoryView[]>(); const [editing, setEditing] = useState<CategoryView>(); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const load = () => { setError(''); adminRequest<CategoryView[]>('/categories').then(setItems).catch(() => setError('No pudimos cargar las categorías.')) }; useEffect(() => { adminRequest<CategoryView[]>('/categories').then(setItems).catch(() => setError('No pudimos cargar las categorías.')) }, [])
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const body = { name: String(f.get('name')), slug: String(f.get('slug')), description: String(f.get('description')), displayOrder: Number(f.get('displayOrder')), active: f.get('active') === 'on' }; try { if (editing) await adminJson(`/categories/${editing.id}`, 'PUT', body); else await adminJson('/categories', 'POST', body); setOpen(false); setEditing(undefined); load() } catch { setError('No fue posible guardar la categoría.') } }
  async function toggle(item: CategoryView) { try { await adminJson(`/categories/${item.id}/active`, 'PATCH', { active: !item.active }); load() } catch { setError('No se pudo actualizar la categoría.') } }
  return <><PageTitle eyebrow="ORGANIZACIÓN DEL MENÚ" title="Categorías" action={<button className="primary" onClick={() => { setEditing(undefined); setOpen(true) }}>Nueva categoría</button>} />{error && <AdminError message={error} retry={load} />}{!items ? <AdminLoading label="Cargando categorías…" /> : !items.length ? <EmptyState text="Aún no hay categorías." /> : <section className="admin-panel category-list">{items.map(item => <article key={item.id}><b className="order-index">{item.displayOrder}</b><div><h2>{item.name}</h2><p>{item.description || 'Sin descripción'} · /{item.slug}</p></div><span>{item.active ? 'Activa' : 'Inactiva'}</span><button className="secondary" onClick={() => { setEditing(item); setOpen(true) }}>Editar</button><button className="secondary" onClick={() => void toggle(item)}>{item.active ? 'Desactivar' : 'Activar'}</button></article>)}</section>}
    {open && <div className="admin-modal" role="dialog" aria-modal="true"><form className="modal-card admin-form" onSubmit={save}><div className="panel-title"><h2>{editing ? 'Editar categoría' : 'Nueva categoría'}</h2><button type="button" className="icon-close" onClick={() => setOpen(false)}>×</button></div><label>Nombre<input name="name" defaultValue={editing?.name} required /></label><label>Slug<input name="slug" defaultValue={editing?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label className="wide">Descripción<textarea name="description" defaultValue={editing?.description} /></label><label>Orden<input name="displayOrder" type="number" min="0" defaultValue={editing?.displayOrder ?? 0} required /></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} /> Activa</label><div className="form-actions wide"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary">Guardar</button></div></form></div>}
  </>
}
