import { useEffect, useState, type FormEvent } from 'react'
import { getAnalytics } from '../api/analytics'
import type { AnalyticsOverview, RankedMetric } from '../types/admin'
import { money } from '../utils/money'
import { PageTitle } from './AdminDashboardPage'
import { AdminError, AdminLoading, EmptyState } from './adminUi'

const iso = (date: Date) => date.toISOString().slice(0, 10)
const initialTo = iso(new Date()); const initialFrom = iso(new Date(Date.now() - 29 * 86400000))
export function AdminAnalyticsPage() {
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(initialTo); const [data, setData] = useState<AnalyticsOverview>(); const [error, setError] = useState('')
  const load = (start = from, end = to) => { setError(''); getAnalytics(start, end).then(setData).catch(() => setError('No pudimos cargar la analítica. Revisa el rango de fechas.')) }
  useEffect(() => { getAnalytics(initialFrom, initialTo).then(setData).catch(() => setError('No pudimos cargar la analítica.')) }, [])
  function filter(event: FormEvent) { event.preventDefault(); load() }
  if (error && !data) return <AdminError message={error} retry={() => load()} />
  return <><PageTitle eyebrow="INTELIGENCIA DEL NEGOCIO" title="Analítica" /><form className="analytics-filter" onSubmit={filter}><label>Desde<input type="date" value={from} onChange={event => setFrom(event.target.value)} required /></label><label>Hasta<input type="date" value={to} onChange={event => setTo(event.target.value)} required /></label><button className="primary">Aplicar rango</button></form>{error && <AdminError message={error} retry={() => load()} />}{!data ? <AdminLoading label="Calculando métricas…" /> : <AnalyticsView data={data} />}</>
}
export function AnalyticsView({ data }: { data: AnalyticsOverview }) {
  const periods = [data.today, data.yesterday, data.week, data.month]
  return <><section className="analytics-periods">{periods.map(period => <article className="metric-card" key={period.label}><span>{period.label}</span><strong>{money(period.sales)}</strong><small>{period.orders} pedidos · <b className={period.changePercentage >= 0 ? 'positive' : 'negative'}>{period.changePercentage >= 0 ? '+' : ''}{period.changePercentage}%</b> vs. período anterior</small></article>)}</section><section className="metric-grid analytics-summary"><article className="metric-card"><span>Pedidos totales</span><strong>{data.totalOrders}</strong></article><article className="metric-card"><span>Cancelados</span><strong>{data.cancelledOrders}</strong></article><article className="metric-card"><span>Ticket promedio</span><strong>{money(data.averageTicket)}</strong></article><article className="metric-card"><span>Descuentos</span><strong>{money(data.discountsApplied)}</strong></article><article className="metric-card"><span>Cupones usados</span><strong>{data.couponUses}</strong></article><article className="metric-card"><span>Puntos ganados/redimidos</span><strong>{data.pointsEarned} / {data.pointsRedeemed}</strong></article></section><section className="analytics-grid"><article className="admin-panel span-2"><h2>Evolución de ventas</h2><SalesChart points={data.salesEvolution} /></article><article className="admin-panel"><h2>Pedidos por día</h2><BarChart values={data.salesEvolution.map(point => ({ label: point.date.slice(5), quantity: point.orders, amount: point.sales }))} value="quantity" /></article><article className="admin-panel"><h2>Productos más vendidos</h2><BarChart values={data.topProducts} value="quantity" /></article><article className="admin-panel"><h2>Métodos de pago</h2><BarChart values={data.paymentMethods} value="quantity" /></article><article className="admin-panel"><h2>Domicilio vs. recoger</h2><BarChart values={data.deliveryTypes} value="quantity" /></article><Ranking title="Categorías más vendidas" values={data.topCategories} /><Ranking title="Horas con más pedidos" values={data.peakHours} /><article className="admin-panel"><h2>Clientes con más compras</h2>{data.topCustomers.length ? data.topCustomers.map(customer => <p key={customer.customerId}><strong>{customer.name}</strong> · {customer.orders} pedidos · {money(customer.amount)}</p>) : <EmptyState text="Sin ventas en el rango." />}</article><article className="admin-panel inventory-alerts"><h2>Alertas de inventario</h2><p><strong>{data.lowStockIngredients}</strong> ingredientes con stock bajo</p><p><strong>{data.outOfStockIngredients}</strong> ingredientes agotados</p></article></section></>
}
export function BarChart({ values, value }: { values: RankedMetric[]; value: 'quantity' | 'amount' }) { const maximum = Math.max(1, ...values.map(item => Number(item[value]))); if (!values.length) return <EmptyState text="Sin datos para graficar." />; return <div className="bar-chart" role="img" aria-label="Gráfica comparativa">{values.slice(0, 8).map(item => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${Number(item[value]) / maximum * 100}%` }} /></i><strong>{value === 'amount' ? money(item.amount) : item.quantity}</strong></div>)}</div> }
export function SalesChart({ points }: { points: AnalyticsOverview['salesEvolution'] }) { if (!points.length) return <EmptyState text="Sin ventas para graficar." />; const max = Math.max(1, ...points.map(point => point.sales)); const coordinates = points.map((point, index) => `${points.length === 1 ? 50 : index / (points.length - 1) * 100},${95 - point.sales / max * 85}`).join(' '); return <div className="sales-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Evolución de ventas por día"><polyline points={coordinates} fill="none" vectorEffect="non-scaling-stroke" /></svg><div>{points.map(point => <span key={point.date}><small>{point.date.slice(5)}</small><strong>{money(point.sales)}</strong></span>)}</div></div> }
function Ranking({ title, values }: { title: string; values: RankedMetric[] }) { return <article className="admin-panel"><h2>{title}</h2>{values.length ? <ol className="top-products">{values.slice(0, 8).map((item, index) => <li key={item.label}><span>{index + 1}</span><strong>{item.label}</strong><b>{item.quantity}</b></li>)}</ol> : <EmptyState text="Sin datos en el rango." />}</article> }
