import { useEffect, useState, type FormEvent } from 'react'
import { adminJson, adminRequest } from '../api/admin'
import type { PromotionView } from '../types/admin'
import { money } from '../utils/money'
import { PageTitle } from './AdminDashboardPage'
import { AdminError, AdminLoading, EmptyState } from './adminUi'
import { dateTime } from './adminFormat'
import { AccessibleModal } from '../components/AccessibleModal'

const localInput = (value?: string) => value ? new Date(value).toISOString().slice(0, 16) : ''
export function AdminPromotionsPage() {
  const [items, setItems] = useState<PromotionView[]>(); const [editing, setEditing] = useState<PromotionView>(); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const load = () => { setError(''); adminRequest<PromotionView[]>('/promotions').then(setItems).catch(() => setError('No pudimos cargar las promociones.')) }; useEffect(() => { adminRequest<PromotionView[]>('/promotions').then(setItems).catch(() => setError('No pudimos cargar las promociones.')) }, [])
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const body = { name: String(f.get('name')), description: String(f.get('description')), discountType: String(f.get('discountType')), discountValue: Number(f.get('discountValue')), startsAt: new Date(String(f.get('startsAt'))).toISOString(), endsAt: new Date(String(f.get('endsAt'))).toISOString(), minimumPurchase: Number(f.get('minimumPurchase')), usageLimit: f.get('usageLimit') ? Number(f.get('usageLimit')) : null, active: f.get('active') === 'on' }; try { if (editing) await adminJson(`/promotions/${editing.id}`, 'PUT', body); else await adminJson('/promotions', 'POST', body); setOpen(false); load() } catch { setError('No fue posible guardar la promoción. Revisa fechas y valores.') } }
  async function toggle(item: PromotionView) { try { await adminJson(`/promotions/${item.id}/active`, 'PATCH', { active: !item.active }); load() } catch { setError('No se pudo actualizar la promoción.') } }
  return <><PageTitle eyebrow="CAMPAÑAS" title="Promociones" action={<button className="primary" onClick={() => { setEditing(undefined); setOpen(true) }}>Nueva promoción</button>} />{error && <AdminError message={error} retry={load} />}{!items ? <AdminLoading label="Cargando promociones…" /> : !items.length ? <EmptyState text="No hay promociones creadas." /> : <section className="promo-grid">{items.map(item => <article className="admin-panel" key={item.id}><p className="eyebrow">{item.active ? 'ACTIVA' : 'INACTIVA'}</p><h2>{item.name}</h2><strong className="promo-value">{item.discountType === 'PERCENTAGE' ? `${item.discountValue}%` : money(item.discountValue)}</strong><p>{item.description}</p><small>{dateTime(item.startsAt)} — {dateTime(item.endsAt)}</small><small>Compra mínima: {money(item.minimumPurchase)} · Límite: {item.usageLimit ?? 'sin límite'}</small><div className="card-actions"><button className="secondary" onClick={() => { setEditing(item); setOpen(true) }}>Editar</button><button className="secondary" onClick={() => void toggle(item)}>{item.active ? 'Desactivar' : 'Activar'}</button></div></article>)}</section>}
    {open && <AccessibleModal labelledBy="promotion-modal-title" onClose={() => setOpen(false)}><form className="modal-card admin-form" onSubmit={save}><div className="panel-title"><h2 id="promotion-modal-title">{editing ? 'Editar promoción' : 'Nueva promoción'}</h2><button type="button" className="icon-close" aria-label="Cerrar editor" onClick={() => setOpen(false)}>×</button></div><label>Nombre<input name="name" defaultValue={editing?.name} required /></label><label>Tipo<select name="discountType" defaultValue={editing?.discountType ?? 'PERCENTAGE'}><option value="PERCENTAGE">Porcentaje</option><option value="FIXED_AMOUNT">Valor fijo</option></select></label><label className="wide">Descripción<textarea name="description" defaultValue={editing?.description} /></label><label>Descuento<input name="discountValue" type="number" min="0" defaultValue={editing?.discountValue} required /></label><label>Compra mínima<input name="minimumPurchase" type="number" min="0" defaultValue={editing?.minimumPurchase ?? 0} required /></label><label>Inicio<input name="startsAt" type="datetime-local" defaultValue={localInput(editing?.startsAt)} required /></label><label>Fin<input name="endsAt" type="datetime-local" defaultValue={localInput(editing?.endsAt)} required /></label><label>Límite de usos<input name="usageLimit" type="number" min="1" defaultValue={editing?.usageLimit} /></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} /> Activa</label><div className="form-actions wide"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary">Guardar</button></div></form></AccessibleModal>}
  </>
}
