import { Link } from 'react-router-dom'
import { ErrorState, LoadingGrid } from '../components/AsyncState'
import { ProductCard } from '../components/ProductCard'
import { useStorefront } from '../features/storefront/storefront-context'
import { formatMoney, toMinorUnits } from '../utils/money'

const dayNames: Record<string, string> = { MONDAY: 'Lun', TUESDAY: 'Mar', WEDNESDAY: 'Mié', THURSDAY: 'Jue', FRIDAY: 'Vie', SATURDAY: 'Sáb', SUNDAY: 'Dom' }
export function HomePage() { const { data, loading, error, retry } = useStorefront(); if (error) return <main className="page"><ErrorState message={error} retry={retry} /></main>; return <main><section className="home-hero"><div className="home-hero__copy"><p className="eyebrow">Bogotá · Hecho al fuego</p><h1>La calle<br /><em>tiene hambre.</em></h1><p>{data?.business.description ?? 'Hamburguesas smash, ingredientes honestos y cero atajos.'}</p><div className="hero-actions"><Link className="button button--acid" to="/menu">Ver menú <span>↘</span></Link><a className="button button--ghost" href="#ubicacion">Dónde estamos</a></div></div><div className="home-hero__visual"><img src="/images/hero-burger.webp" alt="Hamburguesa doble con cheddar, tocineta y papas" fetchPriority="high" /><span className="hero-stamp">SMASHED<br />DAILY</span></div><div className="hero-facts"><span><small>01</small>Carne al fuego</span><span><small>02</small>Pan brioche</span><span><small>03</small>Salsas de casa</span></div></section>
    <section className="section categories-section"><div className="section-heading"><p className="eyebrow">Elige tu mood</p><h2>¿Qué vas a pedir hoy?</h2></div><div className="category-rail">{data?.categories.map((category, index) => <Link to={`/menu?category=${category.slug}`} key={category.id}><span>0{index + 1}</span>{category.name}<b>→</b></Link>)}</div></section>
    <section className="section products-section"><div className="section-heading split"><div><p className="eyebrow">Los más pedidos</p><h2>Favoritos del barrio</h2></div><Link className="text-link" to="/menu">Ver todo el menú →</Link></div>{loading ? <LoadingGrid /> : <div className="product-grid">{data?.products.filter((product) => product.featured).slice(0, 4).map((product) => <ProductCard product={product} currency={data.business.currency} key={product.id} />)}</div>}</section>
    {data?.promotions[0] && <section className="promo-section" id="promociones"><div><p className="eyebrow">Promoción activa</p><h2>{data.promotions[0].name}</h2><p>{data.promotions[0].description}</p><Link className="button button--dark" to="/menu">Quiero la promo →</Link></div><strong>{data.promotions[0].discountType === 'PERCENTAGE' ? `${data.promotions[0].discountValue}%` : formatMoney(toMinorUnits(data.promotions[0].discountValue), data.business.currency)}<small>OFF</small></strong></section>}
    <section className="identity-section"><div className="identity-number">01</div><div><p className="eyebrow">Nuestra forma</p><h2>Menos pose.<br />Más sabor.</h2></div><p>Cada burger se aplasta sobre la plancha al momento. Bordes crujientes, centro jugoso y productos que sí tienen algo que decir.</p></section>
    <section className="location-section" id="ubicacion"><div><p className="eyebrow">Ven al Distrito</p><h2>{data?.business.address ?? 'Bogotá, Colombia'}</h2><p>{data?.business.phone} · WhatsApp {data?.business.whatsapp}</p><div className="schedule">{data?.business.hours.map((hour) => <span key={`${hour.dayOfWeek}-${hour.slotNumber}`}><b>{dayNames[hour.dayOfWeek] ?? hour.dayOfWeek}</b>{hour.closed ? 'Cerrado' : `${hour.opensAt?.slice(0,5)} — ${hour.closesAt?.slice(0,5)}`}</span>)}</div></div><div className="location-art" aria-hidden="true"><span>DS</span><small>BOGOTÁ<br />COLOMBIA</small></div></section>
  </main> }
