import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { trackOrder } from '../api/publicOrders'
import { trackingStorageKey } from '../features/checkout/checkout'
import type { OrderStatus, PaymentStatus, TrackedOrder } from '../types/public'
import { formatMoney, toMinorUnits } from '../utils/money'

const statusLabels: Record<OrderStatus, string> = { NEW: 'Recibido', CONFIRMED: 'Confirmado', PREPARING: 'Preparando', READY: 'Listo', ON_THE_WAY: 'En camino', DELIVERED: 'Entregado', CANCELLED: 'Cancelado' }
const paymentLabels: Record<PaymentStatus, string> = { PENDING: 'Pago pendiente', UNDER_REVIEW: 'Pago en revisión', APPROVED: 'Pago aprobado', REJECTED: 'Comprobante rechazado' }
const deliveryProgress: OrderStatus[] = ['NEW', 'CONFIRMED', 'PREPARING', 'READY', 'ON_THE_WAY', 'DELIVERED']
const pickupProgress: OrderStatus[] = ['NEW', 'CONFIRMED', 'PREPARING', 'READY', 'DELIVERED']

export function OrderConfirmationPage() {
  const { publicNumber = '' } = useParams(); const token = sessionStorage.getItem(trackingStorageKey(publicNumber)); const [order, setOrder] = useState<TrackedOrder | null>(null); const [error, setError] = useState(''); const [refresh, setRefresh] = useState(0); const [loading, setLoading] = useState(Boolean(token))
  useEffect(() => { if (!token) return
    const controller = new AbortController(); trackOrder(publicNumber, token, controller.signal).then(setOrder).catch((reason: unknown) => {
      if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(reason instanceof Error ? reason.message : 'No pudimos consultar el pedido.')
    }).finally(() => setLoading(false)); return () => controller.abort()
  }, [publicNumber, token, refresh])
  if (loading && !order) return <main className="order-page"><section className="state-panel"><span>•••</span><h1>Buscando tu pedido.</h1></section></main>
  if (!order) return <main className="order-page"><section className="state-panel"><span>!</span><h1>No pudimos abrir el seguimiento.</h1><p>{token ? error : 'Este seguimiento necesita el acceso privado guardado al crear el pedido.'}</p><Link className="button button--acid" to="/menu">Volver al menú</Link></section></main>
  const progress = order.deliveryType === 'DELIVERY' ? deliveryProgress : pickupProgress; const current = progress.indexOf(order.status); const whatsApp = order.businessWhatsapp.replace(/\D/g, ''); const message = encodeURIComponent(`Hola, quiero consultar el pedido ${order.publicNumber}. Soy ${order.customerName}.`)
  return <main className="order-page"><section className="order-hero" data-number={order.publicNumber}><div className="order-check">✓</div><p className="eyebrow">Pedido recibido</p><h1>Ya está<br /><i>en marcha.</i></h1><p>Guarda este número para hablar con el restaurante.</p><strong>{order.publicNumber}</strong></section><div className="order-layout"><section className="tracking-card"><div className="tracking-head"><div><p className="eyebrow">Estado actual</p><h2>{statusLabels[order.status]}</h2></div><button type="button" className="button button--outline" disabled={loading} onClick={() => { setLoading(true); setError(''); setRefresh((value) => value + 1) }}>{loading ? 'Actualizando…' : 'Actualizar estado'}</button></div><div className="status-track">{progress.map((status, index) => <div key={status} className={index <= current && order.status !== 'CANCELLED' ? 'active' : ''}><span>{index < current ? '✓' : index + 1}</span><small>{statusLabels[status]}</small></div>)}</div>{error && <div className="checkout-error">{error}</div>}{order.status === 'CANCELLED' && <div className="checkout-error">Este pedido fue cancelado.</div>}{order.loyalty.pointsToEarn > 0 && <div className="loyalty-earned"><strong>+{order.loyalty.pointsToEarn} puntos</strong><span>{order.status === 'DELIVERED' ? 'Ya fueron abonados a tu saldo.' : 'Se abonarán cuando recibas el pedido.'}</span></div>}<div className="confirmation-facts"><div><small>Entrega</small><strong>{order.deliveryType === 'DELIVERY' ? 'Domicilio' : 'Recoger en local'}</strong><p>{order.deliveryAddress ?? 'Distrito Smash'}</p></div><div><small>Tiempo estimado</small><strong>{order.totals.estimatedMinutes} min</strong><p>Desde que recibimos el pedido</p></div><div><small>Pago</small><strong>{paymentLabels[order.paymentStatus]}</strong><p>{order.paymentMethod === 'TRANSFER' ? 'Transferencia' : order.paymentMethod === 'CASH' ? 'Efectivo al recibir' : 'Pago al recoger'}</p></div></div></section><aside className="confirmation-summary"><p className="eyebrow">Resumen</p>{order.items.map((item, index) => <article key={`${item.name}-${index}`}><div><strong>{item.quantity} × {item.name}</strong>{item.extras.length > 0 && <small>+ {item.extras.map((extra) => extra.name).join(', ')}</small>}{item.notes && <small>“{item.notes}”</small>}</div><span>{formatMoney(toMinorUnits(item.subtotal), order.totals.currency)}</span></article>)}<hr /><div><span>Total</span><strong>{formatMoney(toMinorUnits(order.totals.total), order.totals.currency)}</strong></div><a className="button button--acid button--wide" href={`https://wa.me/${whatsApp}?text=${message}`} target="_blank" rel="noreferrer">Contactar por WhatsApp →</a></aside></div></main>
}
