import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getProduct } from '../api/publicCatalog'
import { ProductImage } from '../components/ProductImage'
import { QuantityControl } from '../components/QuantityControl'
import { ErrorState } from '../components/AsyncState'
import { useCart } from '../features/cart/cart-context'
import { useStorefront } from '../features/storefront/storefront-context'
import type { ProductDetail } from '../types/public'
import { formatMoney, toMinorUnits } from '../utils/money'

export function ProductPage() { const { slug = '' } = useParams(); const navigate = useNavigate(); const cart = useCart(); const { data } = useStorefront(); const [product, setProduct] = useState<ProductDetail | null>(null); const [error, setError] = useState<string | null>(null); const [attempt, setAttempt] = useState(0); const [quantity, setQuantity] = useState(1); const [selected, setSelected] = useState<Set<number>>(new Set()); const [notes, setNotes] = useState('')
  useEffect(() => { const controller = new AbortController(); getProduct(slug, controller.signal).then((value) => { setProduct(value); setError(null) }).catch((reason: unknown) => { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(reason instanceof Error ? reason.message : 'No pudimos cargar el producto.') }); return () => controller.abort() }, [slug, attempt])
  const unitTotal = useMemo(() => product ? toMinorUnits(product.price) + product.allowedExtras.filter((extra) => selected.has(extra.id)).reduce((sum, extra) => sum + toMinorUnits(extra.price), 0) : 0, [product, selected])
  if (error) return <main className="page"><ErrorState message={error} retry={() => { setError(null); setProduct(null); setAttempt((value) => value + 1) }} /></main>
  if (!product) return <main className="product-detail loading-detail"><div className="skeleton" /><div className="skeleton" /></main>
  const add = () => { cart.add({ id: crypto.randomUUID(), productId: product.id, slug: product.slug, name: product.name, imagePath: product.imagePath, unitPriceMinor: toMinorUnits(product.price), quantity, notes: notes.trim(), extras: product.allowedExtras.filter((extra) => selected.has(extra.id)).map((extra) => ({ id: extra.id, name: extra.name, unitPriceMinor: toMinorUnits(extra.price) })) }); cart.open() }
  const toggleExtra = (id: number) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next })
  return <main className="product-detail"><button className="back-link" onClick={() => navigate(-1)}>← Volver</button><div className="product-detail__image"><ProductImage src={product.imagePath} alt={product.name} />{product.featured && <span className="badge">Favorita del barrio</span>}</div><div className="product-detail__content"><p className="eyebrow">{product.category.name}</p><h1>{product.name}</h1><p className="product-lead">{product.description}</p><strong className="base-price">Desde {formatMoney(toMinorUnits(product.price), data?.business.currency)}</strong>{product.allowedExtras.length > 0 && <fieldset className="extras-list"><legend>Hazla más tuya <small>Opcional</small></legend>{product.allowedExtras.map((extra) => <label key={extra.id}><input type="checkbox" checked={selected.has(extra.id)} onChange={() => toggleExtra(extra.id)} /><span><b>{extra.name}</b>{extra.description && <small>{extra.description}</small>}</span><strong>+ {formatMoney(toMinorUnits(extra.price), data?.business.currency)}</strong></label>)}</fieldset>}<label className="notes-field"><span>¿Alguna observación? <small>{notes.length}/240</small></span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={240} placeholder="Ej. Sin cebolla, salsa aparte…" rows={3} /></label><div className="product-action"><QuantityControl value={quantity} onChange={setQuantity} /><button className="button button--acid" onClick={add}>Agregar <strong>{formatMoney(unitTotal * quantity, data?.business.currency)}</strong></button></div><p className="price-note">El total final será validado por el restaurante.</p><Link className="text-link" to="/menu">Seguir viendo el menú</Link></div></main> }
